"""
html_renderer.py — Convert pipeline markdown content to styled HTML.

Handles all special formats generated by the novel pipeline:
  - >> lines         → parchment stat block boxes
  - > SIDEBAR: ...   → right-float faction-colored sidebar
  - > SNIPPET: ...   → centered story flavor snippet
  - [DM: ...]        → DM callout boxes (green tint)
  - ## / ### headers → styled headings
  - | tables |       → styled HTML tables
  - **bold** / *italic*
  - --- dividers
  - Paragraphs

Output is a full standalone HTML file with embedded CSS — no external dependencies.
"""

from __future__ import annotations

import logging
import re
import html as _html

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# CSS — embedded in every file
# ---------------------------------------------------------------------------

_CSS = """
/* ── Tower of Last Chance — Mission Module Stylesheet ────────────────────── */
:root {
  --ink:        #1a1208;
  --parchment:  #fdf8f0;
  --gold:       #b8923a;
  --gold-light: #e8c87a;
  --deep:       #1a1208;
  --red-cap:    #7b1e1e;
  --sidebar-bg: #e8f0f8;
  --sidebar-br: #3a6898;
  --dm-bg:      #e8f5e8;
  --dm-br:      #2a6a2a;
  --snippet-bg: #f5f0e4;
  --stat-bg:    #fdf5e0;
  --stat-br:    #b8922a;
  --rule:       #c8a84a;
  --rule-light: #e8d8a0;
  --faction:    #3a6898;
  --body-bg:    #e8e0d0;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: Georgia, 'Times New Roman', serif;
  font-size: 18px;
  line-height: 1.8;
  color: var(--ink);
  background: var(--body-bg);
  padding: 24px 16px;
}

.page {
  max-width: 900px;
  margin: 0 auto;
  background: var(--parchment);
  padding: 0 0 64px;
  box-shadow: 0 4px 24px rgba(0,0,0,0.25);
  border: 1px solid var(--rule);
}

.page-body {
  padding: 40px 56px 0;
}

/* ── Cover ─────────────────────────────────────────────────────────── */
.cover {
  background: linear-gradient(160deg, #1a1208 0%, #2e2010 60%, #1a1208 100%);
  color: #e8d9b4;
  padding: 72px 64px 56px;
  text-align: center;
  border-bottom: 8px solid var(--gold);
  position: relative;
}
.cover::before {
  content: "";
  position: absolute; inset: 0;
  background: url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23c8a84a' fill-opacity='0.04'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
  pointer-events: none;
}
.cover .faction-label {
  font-size: 13px;
  letter-spacing: 5px;
  text-transform: uppercase;
  color: var(--gold-light);
  margin-bottom: 20px;
  font-family: Arial, sans-serif;
}
.cover .ornament {
  color: var(--gold);
  font-size: 28px;
  margin: 12px 0;
  letter-spacing: 8px;
}
.cover h1 {
  font-size: 46px;
  font-weight: bold;
  color: #f5e8c4;
  margin: 8px 0 20px;
  line-height: 1.15;
  text-shadow: 2px 2px 8px rgba(0,0,0,0.5);
}
.cover .subtitle {
  font-size: 16px;
  color: #c8b880;
  font-style: italic;
  margin-bottom: 28px;
}
.cover .meta-block {
  display: inline-block;
  border: 1px solid #6a5030;
  background: rgba(0,0,0,0.3);
  padding: 12px 28px;
  margin-top: 16px;
  font-size: 14px;
  color: #b0a070;
  font-family: Arial, sans-serif;
  line-height: 2;
}

/* ── Typography ─────────────────────────────────────────────────────── */
h1 {
  font-size: 34px; color: var(--deep); margin: 44px 0 20px; line-height: 1.2;
  border-bottom: 3px solid var(--gold); padding-bottom: 8px;
}
h2 {
  font-size: 26px; color: var(--red-cap); margin: 40px 0 16px;
  border-bottom: 2px solid var(--rule-light); padding-bottom: 6px;
  font-variant: small-caps; letter-spacing: 1px;
}
h3 {
  font-size: 20px; color: var(--faction); margin: 28px 0 10px;
  font-variant: small-caps;
}
h4 { font-size: 18px; font-weight: bold; color: #444; margin: 20px 0 8px; }

p  { margin: 0 0 18px; }
p:last-child { margin-bottom: 0; }

hr {
  border: none;
  background: linear-gradient(to right, transparent, var(--gold) 20%, var(--gold) 80%, transparent);
  height: 2px;
  margin: 36px 0;
}

strong { font-weight: bold; color: #2a1808; }
em     { font-style: italic; }

/* Drop-cap on first paragraph after a chapter header */
.chapter-first-para::first-letter {
  float: left;
  font-size: 64px;
  line-height: 0.8;
  padding: 8px 10px 0 0;
  color: var(--red-cap);
  font-family: Georgia, serif;
  font-weight: bold;
}

/* ── Lists ────────────────────────────────────────────────────────────── */
ul, ol { margin: 0 0 18px 32px; }
li     { margin-bottom: 7px; line-height: 1.7; }

/* ── Tables ─────────────────────────────────────────────────────────── */
table  { width: 100%; border-collapse: collapse; margin: 24px 0 28px; font-size: 15px; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }
th     { background: var(--deep); color: var(--gold-light); font-weight: bold; padding: 10px 12px; border: 1px solid #555; text-align: left; font-family: Arial, sans-serif; font-size: 13px; letter-spacing: 1px; text-transform: uppercase; }
td     { padding: 9px 12px; border: 1px solid #d0c8b0; vertical-align: top; }
tr:nth-child(even) td { background: rgba(200,168,74,0.06); }
tr:hover td { background: rgba(200,168,74,0.12); }

/* ── READ ALOUD box ─────────────────────────────────────────────────── */
.read-aloud {
  background: #f0f4f8;
  border-left: 6px solid #3a6898;
  border-radius: 0 6px 6px 0;
  padding: 16px 22px;
  margin: 20px 0;
  font-style: italic;
  font-size: 17px;
  color: #1a2a3a;
  line-height: 1.85;
  box-shadow: 0 2px 6px rgba(58,104,152,0.1);
}
.read-aloud .ra-label {
  font-weight: bold;
  font-style: normal;
  color: #3a6898;
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 3px;
  font-family: Arial, sans-serif;
  display: block;
  margin-bottom: 8px;
}

/* ── GM NOTE box ─────────────────────────────────────────────────────── */
.gm-note {
  background: #fef9e7;
  border: 1px solid #d4a836;
  border-left: 5px solid #c8861a;
  border-radius: 0 6px 6px 0;
  padding: 12px 18px;
  margin: 16px 0;
  font-size: 14px;
  color: #3a2800;
  font-family: Arial, sans-serif;
  line-height: 1.65;
}
.gm-note .gm-label {
  font-weight: bold;
  color: #c8861a;
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 2px;
  display: block;
  margin-bottom: 6px;
  font-family: Arial, sans-serif;
}

/* ── DIALOG TABLE ────────────────────────────────────────────────── */
.dialog-block {
  background: #f4f0fa;
  border: 1px solid #8a6abf;
  border-left: 5px solid #6b3fa0;
  border-radius: 6px;
  padding: 14px 18px 12px;
  margin: 20px 0;
  page-break-inside: avoid;
}
.dialog-block .dialog-label {
  font-weight: bold;
  color: #5a2d8a;
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 2px;
  display: block;
  margin-bottom: 10px;
  font-family: Arial, sans-serif;
}
.dialog-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 14px;
  line-height: 1.5;
}
.dialog-table th {
  background: #6b3fa0;
  color: #fff;
  padding: 6px 10px;
  text-align: left;
  font-family: Arial, sans-serif;
  font-size: 11px;
  letter-spacing: .05em;
}
.dialog-table td {
  padding: 6px 10px;
  border-bottom: 1px solid #d0c0e8;
  vertical-align: top;
}
.dialog-table tr:last-child td { border-bottom: none; }
.dialog-table tr:nth-child(even) td { background: rgba(107,63,160,.05); }
.dialog-trigger { font-style: italic; color: #3a2060; }
.dialog-response { color: #1a1208; }

/* ── VISUAL CLUES ────────────────────────────────────────────────── */
.clue-block {
  background: #f0f8f0;
  border: 1px solid #5a8a5a;
  border-left: 5px solid #2a6a2a;
  border-radius: 6px;
  padding: 14px 18px 12px;
  margin: 20px 0;
  page-break-inside: avoid;
}
.clue-block .clue-label {
  font-weight: bold;
  color: #2a5a2a;
  font-size: 10px;
  text-transform: uppercase;
  letter-spacing: 2px;
  display: block;
  margin-bottom: 8px;
  font-family: Arial, sans-serif;
}
.clue-block ul { margin: 0; padding-left: 18px; }
.clue-block li { margin-bottom: 6px; font-size: 14px; line-height: 1.5; }
.clue-block li strong { color: #1a4a1a; }

/* ── LEAVING THE SCENE ───────────────────────────────────────────── */
.leaving-block {
  background: #fff8ee;
  border: 1px solid #c8861a;
  border-left: 5px solid #b8621a;
  border-radius: 8px;
  padding: 18px 20px 16px;
  margin: 24px 0;
  page-break-inside: avoid;
}
.leaving-label {
  font-weight: bold;
  color: #8a4a10;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 2px;
  display: block;
  margin-bottom: 16px;
  font-family: Arial, sans-serif;
}
/* Stack key above val — much more readable on tablet */
.leaving-grid { display: flex; flex-direction: column; gap: 14px; margin-bottom: 16px; }
.leaving-row { display: flex; flex-direction: column; gap: 3px; }
.leaving-key {
  font-family: Arial, sans-serif;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: .12em;
  text-transform: uppercase;
  color: #a06020;
}
.leaving-val {
  color: #1a1208;
  font-size: 15px;
  line-height: 1.65;
}
.leaving-lingers {
  font-style: italic;
  color: #5a3a10;
  font-size: 15px;
  line-height: 1.65;
}
/* Divider between grid and routes */
.leaving-departures-label {
  font-family: Arial, sans-serif;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: .12em;
  text-transform: uppercase;
  color: #a06020;
  margin: 4px 0 10px;
  padding-top: 14px;
  border-top: 1px solid rgba(184,98,26,.2);
}
/* Route cards — no bullet, each option its own pill */
.leaving-departures { margin: 0; padding: 0; list-style: none; display: flex; flex-direction: column; gap: 8px; }
.leaving-departures li {
  font-size: 15px;
  line-height: 1.65;
  color: #1a1208;
  background: rgba(184,98,26,.06);
  border-left: 3px solid rgba(184,98,26,.35);
  border-radius: 0 5px 5px 0;
  padding: 8px 12px;
}

/* ── DM Callout [DM: ...] ─────────────────────────────────────────── */
.dm-note {
  background: var(--dm-bg);
  border-left: 5px solid var(--dm-br);
  border-radius: 0 6px 6px 0;
  padding: 12px 18px;
  margin: 16px 0;
  font-size: 15px;
  color: #1a3a1a;
  font-family: Arial, sans-serif;
  line-height: 1.6;
}
.dm-note .dm-label {
  font-weight: bold;
  color: var(--dm-br);
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 2px;
  display: block;
  margin-bottom: 4px;
}

/* ── Numbered area header (N - Name) ─────────────────────────────────── */
.area-header {
  background: linear-gradient(90deg, var(--red-cap) 0%, #6a1a1a 100%);
  color: #f5e8c0;
  padding: 10px 20px 10px 16px;
  margin: 32px 0 16px;
  font-family: Arial, sans-serif;
  font-size: 15px;
  font-weight: bold;
  letter-spacing: 0.5px;
  display: flex;
  align-items: center;
  gap: 14px;
  border-radius: 4px;
  box-shadow: 0 2px 6px rgba(0,0,0,0.15);
}
.area-header .area-num {
  background: rgba(255,255,255,0.15);
  border: 1px solid rgba(255,255,255,0.3);
  min-width: 28px;
  height: 28px;
  display: flex; align-items: center; justify-content: center;
  border-radius: 3px;
  font-size: 14px;
  flex-shrink: 0;
}
.area-header .area-name {
  font-variant: small-caps;
  letter-spacing: 1px;
}

/* ── Section labels (👤 NPCs PRESENT, 🎲 MECHANICS, etc.) ────────────── */
.scene-section {
  margin: 14px 0 6px;
  padding: 6px 14px;
  font-family: Arial, sans-serif;
  font-size: 12px;
  font-weight: bold;
  letter-spacing: 2px;
  text-transform: uppercase;
  color: var(--red-cap);
  border-bottom: 1px solid var(--rule-light);
}

/* ── Transition line ─────────────────────────────────────────────────── */
.transition {
  background: linear-gradient(90deg, transparent, rgba(200,168,74,0.15), transparent);
  border-top: 1px dashed var(--gold);
  border-bottom: 1px dashed var(--gold);
  padding: 8px 20px;
  margin: 20px 0;
  font-style: italic;
  font-size: 14px;
  font-family: Arial, sans-serif;
  color: #5a4020;
  text-align: center;
}

/* ── SIDEBAR ─────────────────────────────────────────────────────────── */
.sidebar {
  float: right;
  width: 36%;
  margin: 4px 0 20px 28px;
  background: var(--sidebar-bg);
  border: 1px solid var(--sidebar-br);
  border-top: 4px solid var(--sidebar-br);
  padding: 16px 18px;
  font-size: 14px;
  font-family: Arial, sans-serif;
  line-height: 1.65;
  border-radius: 0 4px 4px 4px;
  box-shadow: 2px 2px 8px rgba(0,0,0,0.1);
}
.sidebar .sidebar-title {
  font-size: 11px;
  font-weight: bold;
  text-transform: uppercase;
  letter-spacing: 3px;
  color: var(--sidebar-br);
  margin-bottom: 10px;
  padding-bottom: 6px;
  border-bottom: 1px solid rgba(58,104,152,0.3);
}
.clearfix::after { content: ""; display: table; clear: both; }

/* ── SNIPPET ────────────────────────────────────────────────────────── */
.snippet {
  background: var(--snippet-bg);
  border-top: 1px solid var(--rule);
  border-bottom: 1px solid var(--rule);
  padding: 16px 32px;
  margin: 24px 0;
  font-style: italic;
  font-size: 15px;
  color: #444;
  text-align: center;
}
.snippet::before, .snippet::after {
  content: "— — — — — — — — — —";
  display: block;
  color: #bbb;
  font-style: normal;
  font-size: 13px;
  margin: 4px 0;
}

/* ── STAT BLOCK (>> lines) ──────────────────────────────────────────── */
.stat-block {
  background: var(--stat-bg);
  border: 2px solid var(--stat-br);
  border-top: 4px solid var(--stat-br);
  padding: 16px 20px;
  margin: 24px 0;
  font-size: 14px;
  font-family: Arial, sans-serif;
  line-height: 1.65;
  box-shadow: inset 0 0 0 1px rgba(200,168,74,0.3), 2px 2px 6px rgba(0,0,0,0.1);
  position: relative;
}
.stat-block::before {
  content: "◆";
  position: absolute;
  top: -14px; left: 50%;
  transform: translateX(-50%);
  background: var(--stat-bg);
  padding: 0 8px;
  color: var(--stat-br);
  font-size: 16px;
}
.stat-block .stat-line { margin-bottom: 4px; }
.stat-block .stat-divider {
  border: none;
  border-top: 1px solid var(--stat-br);
  margin: 10px 0;
  opacity: 0.5;
}

/* ── Chapter header ──────────────────────────────────────────────────── */
.chapter-header {
  background: linear-gradient(135deg, #1a1208 0%, #2e200e 100%);
  color: #e8d9b4;
  padding: 28px 56px 24px;
  margin-bottom: 36px;
  border-bottom: 5px solid var(--gold);
  position: relative;
}
.chapter-header::after {
  content: "";
  position: absolute;
  bottom: -9px; left: 40px;
  width: 60px; height: 5px;
  background: var(--gold-light);
}
.chapter-header .ch-label {
  font-size: 11px;
  letter-spacing: 4px;
  text-transform: uppercase;
  color: var(--gold-light);
  font-family: Arial, sans-serif;
  margin-bottom: 8px;
}
.chapter-header h2 {
  font-size: 30px;
  color: #f5e8c0;
  border: none;
  margin: 0;
  padding: 0;
  font-variant: normal;
  letter-spacing: 0;
}

/* ── Index page ──────────────────────────────────────────────────────── */
.index-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;
  margin-top: 28px;
}
.index-card {
  background: white;
  border: 1px solid var(--rule-light);
  border-top: 5px solid var(--faction);
  padding: 22px;
  border-radius: 0 0 6px 6px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.08);
  transition: box-shadow 0.2s;
}
.index-card:hover { box-shadow: 0 4px 16px rgba(0,0,0,0.15); }
.index-card h3 { margin: 0 0 10px; color: var(--red-cap); border: none; font-size: 18px; }
.index-card a  {
  color: var(--faction); text-decoration: none; font-weight: bold;
  font-size: 20px;
}
.index-card a:hover { text-decoration: underline; color: var(--red-cap); }
.index-card p { font-size: 14px; color: #666; margin-top: 8px; line-height: 1.6; }
.index-card .card-icon { font-size: 28px; margin-bottom: 10px; display: block; }
/* Component icon map */
.icon-dm_guide::before     { content: "📖"; }
.icon-module::before       { content: "⚔️"; }
.icon-players_guide::before{ content: "🗺️"; }
.icon-maps::before         { content: "🗺️"; }
.icon-chart_pack::before   { content: "📊"; }
.icon-chapters::before     { content: "📚"; }

/* ── Navigation bar ──────────────────────────────────────────────────── */
.nav-bar {
  background: var(--deep);
  padding: 10px 56px;
  border-bottom: 2px solid var(--gold);
  font-family: Arial, sans-serif;
  font-size: 13px;
  display: flex;
  align-items: center;
}
.nav-bar a {
  color: var(--gold-light);
  text-decoration: none;
  margin-right: 20px;
}
.nav-bar a:hover { color: white; text-decoration: underline; }

/* ── Responsive ──────────────────────────────────────────────────────── */
@media (max-width: 640px) {
  body { padding: 0; }
  .page { box-shadow: none; }
  .page-body { padding: 24px 20px 0; }
  .cover { padding: 40px 24px; }
  .chapter-header { padding: 20px 20px 16px; }
  .sidebar { float: none; width: 100%; margin: 16px 0; }
  .index-grid { grid-template-columns: 1fr; }
  .nav-bar { padding: 10px 20px; }
  h1 { font-size: 26px; }
  h2 { font-size: 22px; }
}

@media print {
  body { background: white; padding: 0; }
  .page { box-shadow: none; }
  .page-body { padding: 20px 40px 0; }
  .chapter-header { padding: 16px 40px; }
  .sidebar { float: none; width: 100%; margin: 16px 0; }
  .nav-bar { display: none; }
  .index-grid { grid-template-columns: 1fr 1fr; }
}
"""


# ---------------------------------------------------------------------------
# Inline markdown → HTML
# ---------------------------------------------------------------------------

def _inline(text: str) -> str:
    """Convert inline markdown (bold, italic, code) to HTML."""
    text = _html.escape(text)
    # Bold-italic
    text = re.sub(r'\*\*\*(.+?)\*\*\*', r'<strong><em>\1</em></strong>', text)
    # Bold
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    # Italic
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    # Inline code
    text = re.sub(r'`(.+?)`', r'<code>\1</code>', text)
    return text


# ---------------------------------------------------------------------------
# Block parser
# ---------------------------------------------------------------------------

def _parse_blocks(md: str) -> str:
    """Convert markdown text to HTML blocks."""
    lines    = md.splitlines()
    out      = []
    i        = 0
    stat_buf: list[str] = []
    in_table = False
    table_rows: list[list[str]] = []

    def flush_stat():
        if not stat_buf:
            return
        out.append('<div class="stat-block">')
        for ln in stat_buf:
            if re.match(r'^[-─═]{3,}$', ln.strip()):
                out.append('<div class="stat-divider"></div>')
            else:
                out.append(f'<div class="stat-line">{_inline(ln)}</div>')
        out.append('</div>')
        stat_buf.clear()

    def flush_table():
        if not table_rows:
            return
        out.append('<table>')
        for ri, row in enumerate(table_rows):
            tag = 'th' if ri == 0 else 'td'
            out.append('<tr>' + ''.join(f'<{tag}>{_inline(c)}</{tag}>' for c in row) + '</tr>')
        out.append('</table>')
        table_rows.clear()

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # ── Stat block lines (>> prefix) ──────────────────────────────
        if stripped.startswith('>> '):
            flush_table()
            stat_buf.append(stripped[3:])
            i += 1
            continue

        # Flush stat block if we hit a non->> line
        if stat_buf:
            flush_stat()

        # ── Table rows ─────────────────────────────────────────────────
        if stripped.startswith('|') and stripped.endswith('|'):
            if re.match(r'^\|[\s\-:|]+\|$', stripped):
                i += 1
                continue
            cells = [c.strip() for c in stripped.split('|') if c.strip()]
            table_rows.append(cells)
            i += 1
            continue

        if table_rows:
            flush_table()

        # ── READ ALOUD block ───────────────────────────────────────────
        # Matches: "📖 READ ALOUD:", "Read this:", "READ ALOUD:"
        if re.match(r'^(📖\s*)?READ\s+ALOUD\s*:', stripped, re.IGNORECASE) or \
           re.match(r'^Read\s+this\s*:', stripped, re.IGNORECASE):
            # Collect all following lines until next section marker or blank+non-indent
            label = re.sub(r'^(📖\s*)?READ\s+ALOUD\s*:|^Read\s+this\s*:', '', stripped, flags=re.IGNORECASE).strip()
            ra_lines = []
            if label:
                ra_lines.append(label)
            i += 1
            while i < len(lines):
                nxt = lines[i].strip()
                # Stop on a new section marker, blank line followed by new section, heading
                if not nxt:
                    # Peek ahead
                    if i + 1 < len(lines) and re.match(
                        r'^(📝|📋|👤|🎲|⚡|➡️|GM\s*NOTE|DM\s*NOTE|#{1,4}\s|>>)',
                        lines[i + 1].strip(), re.IGNORECASE
                    ):
                        break
                    ra_lines.append('')
                    i += 1
                    continue
                if re.match(r'^(📝|📋|👤|🎲|⚡|➡️|GM\s*NOTE|DM\s*NOTE|#)', nxt, re.IGNORECASE):
                    break
                ra_lines.append(nxt)
                i += 1
            content_html = ' '.join(ra_lines).strip()
            out.append(
                '<div class="read-aloud">'
                '<span class="ra-label">📖 Read Aloud to Players</span>'
                f'{_inline(content_html)}'
                '</div>'
            )
            continue

        # ── GM NOTE / DM NOTE box ──────────────────────────────────────
        if re.match(r'^(📝\s*)?(?:GM|DM)\s*NOTE\s*:', stripped, re.IGNORECASE) or \
           re.match(r'^(📝\s*DM\s+NOTES?)\s*:', stripped, re.IGNORECASE):
            label_text = re.sub(r'^(📝\s*)?(?:GM|DM)\s*NOTES?\s*:', '', stripped, flags=re.IGNORECASE).strip()
            note_lines = []
            if label_text:
                note_lines.append(label_text)
            i += 1
            while i < len(lines):
                nxt = lines[i].strip()
                if not nxt or re.match(r'^(📖|📋|👤|🎲|⚡|➡️|READ\s+ALOUD|Read\s+this|#{1,4}\s|>>)', nxt, re.IGNORECASE):
                    break
                note_lines.append(nxt)
                i += 1
            content_html = '<br>'.join(_inline(ln) for ln in note_lines if ln)
            out.append(
                '<div class="gm-note">'
                '<span class="gm-label">📝 GM / DM Only</span>'
                f'{content_html}'
                '</div>'
            )
            continue

        # ── Numbered area header: "N - Area Name" or "Area N. Name" ──
        m_area = re.match(r'^(\d+)\s*[-–.]\s*(.+)$', stripped)
        if m_area and len(stripped) < 80:
            num = m_area.group(1)
            name = m_area.group(2).strip()
            out.append(
                f'<div class="area-header">'
                f'<span class="area-num">{_html.escape(num)}</span>'
                f'<span class="area-name">{_inline(name)}</span>'
                f'</div>'
            )
            i += 1
            continue

        # ── Scene section labels (👤 NPCs PRESENT:, 🎲 MECHANICS:, etc.) ──
        m_sec = re.match(
            r'^(👤\s*NPCs?\s*PRESENT|🎲\s*MECHANICS?|⚡\s*WHAT\s*HAPPENS?|'
            r'📝\s*DM\s*NOTES?|👤\s*NPC|Actions?|Reactions?|Legendary\s*Actions?)\s*:?\s*$',
            stripped, re.IGNORECASE
        )
        if m_sec:
            out.append(f'<div class="scene-section">{_html.escape(stripped.lstrip("📖📝👤🎲⚡").strip())}</div>')
            i += 1
            continue

        # ── Transition line ➡️ TRANSITION: ──────────────────────────────
        if re.match(r'^➡️?\s*TRANSITION\s*:', stripped, re.IGNORECASE):
            content = re.sub(r'^➡️?\s*TRANSITION\s*:\s*', '', stripped, flags=re.IGNORECASE)
            out.append(f'<div class="transition">➡ {_inline(content)}</div>')
            i += 1
            continue

        # ── SIDEBAR ────────────────────────────────────────────────────
        if re.match(r'^>?\s*SIDEBAR:\s*', stripped, re.IGNORECASE):
            content = re.sub(r'^>?\s*SIDEBAR:\s*', '', stripped, flags=re.IGNORECASE)
            out.append(
                '<div class="sidebar">'
                '<div class="sidebar-title">◆ Sidebar</div>'
                f'<p>{_inline(content)}</p>'
                '</div>'
            )
            i += 1
            continue

        # ── SNIPPET ────────────────────────────────────────────────────
        if re.match(r'^>?\s*SNIPPET:\s*', stripped, re.IGNORECASE):
            content = re.sub(r'^>?\s*SNIPPET:\s*', '', stripped, flags=re.IGNORECASE)
            out.append(f'<div class="snippet">{_inline(content)}</div>')
            i += 1
            continue

        # ── DM note [DM: ...] ──────────────────────────────────────────
        m = re.match(r'^\[DM:\s*(.*?)\]$', stripped, re.IGNORECASE)
        if m:
            out.append(
                f'<div class="dm-note">'
                f'<span class="dm-label">DM Note</span>'
                f'{_inline(m.group(1))}'
                f'</div>'
            )
            i += 1
            continue

        # Generic blockquote (> text)
        if stripped.startswith('> '):
            content = stripped[2:]
            out.append(f'<blockquote><p>{_inline(content)}</p></blockquote>')
            i += 1
            continue

        # ── Headings ───────────────────────────────────────────────────
        if stripped.startswith('#### '):
            out.append(f'<h4>{_inline(stripped[5:])}</h4>')
            i += 1
            continue
        if stripped.startswith('### '):
            out.append(f'<h3>{_inline(stripped[4:])}</h3>')
            i += 1
            continue
        if stripped.startswith('## '):
            out.append(f'<h2>{_inline(stripped[3:])}</h2>')
            i += 1
            continue
        if stripped.startswith('# '):
            out.append(f'<h1>{_inline(stripped[2:])}</h1>')
            i += 1
            continue

        # ── Horizontal rule ────────────────────────────────────────────
        if re.match(r'^[-*_]{3,}$', stripped):
            out.append('<hr>')
            i += 1
            continue

        # ── Bullet list ────────────────────────────────────────────────
        if re.match(r'^[-*]\s+', stripped):
            items = []
            while i < len(lines) and re.match(r'^[-*]\s+', lines[i].strip()):
                items.append(f'<li>{_inline(lines[i].strip()[2:])}</li>')
                i += 1
            out.append('<ul>' + ''.join(items) + '</ul>')
            continue

        # ── Numbered list ──────────────────────────────────────────────
        if re.match(r'^\d+\.\s+', stripped):
            items = []
            while i < len(lines) and re.match(r'^\d+\.\s+', lines[i].strip()):
                content = re.sub(r'^\d+\.\s+', '', lines[i].strip())
                items.append(f'<li>{_inline(content)}</li>')
                i += 1
            out.append('<ol>' + ''.join(items) + '</ol>')
            continue

        # ── Empty line ─────────────────────────────────────────────────
        if not stripped:
            i += 1
            continue

        # ── Paragraph ─────────────────────────────────────────────────
        # Accumulate consecutive non-empty, non-special lines
        para_lines = []
        while i < len(lines):
            ln = lines[i].strip()
            if not ln:
                break
            if ln.startswith(('>> ', '> ', '#', '|', '-', '*', '[DM:')):
                break
            if re.match(r'^\d+\.\s+', ln):
                break
            para_lines.append(_inline(ln))
            i += 1
        if para_lines:
            out.append('<p>' + ' '.join(para_lines) + '</p>')
        else:
            i += 1

    flush_stat()
    flush_table()

    return '\n'.join(out)


# ---------------------------------------------------------------------------
# Full page wrapper
# ---------------------------------------------------------------------------

def _faction_color(faction: str) -> str:
    _map = {
        "iron fang":           "#8B4513",
        "argent blades":       "#808080",
        "glass sigil":         "#4682B4",
        "serpent choir":       "#DAA520",
        "obsidian lotus":      "#6B3FA0",
        "patchwork saints":    "#8B0000",
        "wardens of ash":      "#A0522D",
        "tower authority":     "#2F4F4F",
        "adventurers guild":   "#2E7D32",
        "guild of ashen scrolls":"#8D6E3A",
    }
    f = (faction or "").lower()
    for k, v in _map.items():
        if k in f:
            return v
    return "#3a6898"


def _page(title: str, content_html: str, faction: str = "",
          mission_id: int | None = None) -> str:
    fc  = _faction_color(faction)
    css = _CSS.replace("--faction:    #3a6898;", f"--faction:    {fc};")

    nav = (
        '<nav class="nav-bar">'
        '<a href="/" style="margin-right:24px;opacity:.7;">⬅ Dashboard</a>'
        '<a href="index.html">◀ Index</a>'
        '<span style="color:#6a5030;font-family:Arial,sans-serif;font-size:13px;margin-left:auto;">'
        'Tower of Last Chance — D&amp;D 5e 2024'
        '</span>'
        '</nav>'
    )

    mid_js = f"const MISSION_ID = {mission_id};" if mission_id else "const MISSION_ID = null;"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_html.escape(title)}</title>
<style>{css}</style>
<script>{mid_js}</script>
</head>
<body>
<div class="page clearfix">
{nav}
{content_html}
</div>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Structured module renderer — bypasses _parse_blocks for clean output
# ---------------------------------------------------------------------------

def _esc(t: str) -> str:
    return _html.escape(str(t or ""))


def _md(t: str) -> str:
    """Inline markdown on escaped text."""
    return _inline(str(t or ""))


def _render_stat_block(sb: dict) -> str:
    """Render one stat block dict into a styled HTML box."""
    lines = []
    name_line = _esc(sb.get("name", "Unknown"))
    count = sb.get("count", 1)
    if count and int(count) > 1:
        name_line += f" <span style='font-weight:normal;font-size:13px'>(×{count})</span>"
    lines.append(f'<div class="stat-line" style="font-size:17px;font-weight:bold;color:#2a0808;margin-bottom:6px">{name_line}</div>')
    if sb.get("size_type"):
        lines.append(f'<div class="stat-line" style="font-style:italic;color:#555;margin-bottom:8px">{_esc(sb["size_type"])}</div>')
    lines.append('<div class="stat-divider"></div>')
    for key in ("ac", "hp", "speed"):
        if sb.get(key):
            label = {"ac": "Armor Class", "hp": "Hit Points", "speed": "Speed"}[key]
            lines.append(f'<div class="stat-line"><strong>{label}</strong> {_esc(sb[key])}</div>')
    if sb.get("stats"):
        lines.append('<div class="stat-divider"></div>')
        lines.append(f'<div class="stat-line" style="font-family:Arial,sans-serif;font-size:13px">{_esc(sb["stats"])}</div>')
    lines.append('<div class="stat-divider"></div>')
    for key in ("saves", "skills", "resistances", "immunities", "senses", "languages", "cr"):
        if sb.get(key):
            label = key.replace("_", " ").title()
            if key == "cr":
                label = "Challenge"
            lines.append(f'<div class="stat-line"><strong>{label}</strong> {_esc(sb[key])}</div>')
    if sb.get("traits"):
        lines.append('<div class="stat-divider"></div>')
        for trait in sb["traits"]:
            lines.append(f'<div class="stat-line">{_md(trait)}</div>')
    if sb.get("actions"):
        lines.append('<div class="stat-divider"></div>')
        lines.append('<div class="stat-line" style="font-variant:small-caps;font-weight:bold;letter-spacing:1px;color:#7b1e1e;font-size:15px">Actions</div>')
        for action in sb["actions"]:
            lines.append(f'<div class="stat-line">{_md(action)}</div>')
    if sb.get("tactics"):
        lines.append('<div class="stat-divider"></div>')
        lines.append(f'<div class="stat-line" style="font-style:italic;color:#3a3a3a">'
                     f'<strong>Tactics:</strong> {_esc(sb["tactics"])}</div>')
    if sb.get("if_lose"):
        lines.append(f'<div class="stat-line" style="font-style:italic;color:#5a2020">'
                     f'<strong>If players lose:</strong> {_esc(sb["if_lose"])}</div>')
    return (
        '<div class="stat-block">'
        + "\n".join(lines) +
        '</div>'
    )


def _render_npc_block(npc: dict) -> str:
    """Render one NPC truth sheet."""
    name = _esc(npc.get("name", "Unknown NPC"))
    role = _esc(npc.get("role", ""))
    lines = [
        f'<div style="margin:16px 0 8px;padding:10px 16px;background:#f8f4ec;'
        f'border-left:4px solid #b8923a;border-radius:0 4px 4px 0">',
        f'<div style="font-weight:bold;font-size:16px;color:#2a1808">{name}'
        + (f' <span style="font-weight:normal;font-style:italic;color:#666;font-size:14px">— {role}</span>' if role else "")
        + '</div>',
    ]
    for field in ("wants", "knows", "hides"):
        if npc.get(field):
            label = field.capitalize()
            lines.append(
                f'<div style="font-family:Arial,sans-serif;font-size:14px;margin-top:4px">'
                f'<span style="font-weight:bold;color:#7b1e1e;text-transform:uppercase;'
                f'font-size:11px;letter-spacing:1px">{label}:</span> '
                f'{_esc(npc[field])}</div>'
            )
    if npc.get("branches"):
        for branch in npc["branches"]:
            lines.append(
                f'<div style="font-family:Arial,sans-serif;font-size:13px;'
                f'margin-top:6px;padding:6px 10px;background:#f0f0e8;'
                f'border-radius:3px;border-left:2px solid #c8a84a">'
                f'{_md(branch)}</div>'
            )
    lines.append('</div>')
    return "\n".join(lines)


def _render_scene(scene: dict) -> str:
    """Render one complete scene section."""
    num   = str(scene.get("num", "?"))
    name  = _esc(scene.get("name", "").upper())
    parts = []

    # Area header
    parts.append(
        f'<div class="area-header" style="margin-top:48px">'
        f'<span class="area-num">{num}</span>'
        f'<span class="area-name">{name}</span>'
        f'</div>'
    )

    # Read-aloud
    if scene.get("read_aloud"):
        parts.append(
            '<div class="read-aloud">'
            '<span class="ra-label">📖 Read Aloud to Players</span>'
            f'<em>{_esc(scene["read_aloud"])}</em>'
            '</div>'
        )

    # GM note
    if scene.get("gm_note"):
        note_html = "<br>".join(_md(ln) for ln in scene["gm_note"].splitlines() if ln.strip())
        parts.append(
            '<div class="gm-note">'
            '<span class="gm-label">📝 GM / DM Only</span>'
            f'{note_html}'
            '</div>'
        )

    # NPCs
    if scene.get("npcs"):
        parts.append('<div class="scene-section">👤 NPCs Present</div>')
        for npc in scene["npcs"]:
            parts.append(_render_npc_block(npc))

    # Mechanics / branches (non-NPC-specific)
    if scene.get("mechanics"):
        parts.append('<div class="scene-section">🎲 Mechanics &amp; Branches</div>')
        mech_lines = []
        for m in scene["mechanics"]:
            mech_lines.append(f'<li style="margin-bottom:8px">{_md(m)}</li>')
        parts.append('<ul style="margin:8px 0 0 20px;font-family:Arial,sans-serif;font-size:15px">'
                     + "".join(mech_lines) + '</ul>')

    # Clues
    if scene.get("clues"):
        parts.append('<div class="scene-section">🔍 Three-Clue Structure</div>')
        clue_lines = "".join(
            f'<li style="margin-bottom:6px"><strong>{_esc(c.split(":")[0])}:</strong> '
            f'{_esc(":".join(c.split(":")[1:]).strip())}</li>'
            if ":" in c else f'<li>{_esc(c)}</li>'
            for c in scene["clues"]
        )
        parts.append(f'<ul style="margin:8px 0 0 20px;font-family:Arial,sans-serif;font-size:15px">{clue_lines}</ul>')

    # Stat blocks
    if scene.get("stat_blocks"):
        parts.append('<div class="scene-section">⚔️ Stat Blocks</div>')
        for sb in scene["stat_blocks"]:
            parts.append(_render_stat_block(sb))

    # What happens / outcome bullets
    if scene.get("what_happens"):
        parts.append('<div class="scene-section">⚡ What Happens</div>')
        wh_lines = "".join(
            f'<li style="margin-bottom:8px">{_md(item)}</li>'
            for item in scene["what_happens"]
        )
        parts.append('<ul style="margin:8px 0 0 20px;font-family:Arial,sans-serif;font-size:15px">'
                     + wh_lines + '</ul>')

    # Transition
    if scene.get("transition"):
        parts.append(f'<div class="transition">➡ {_esc(scene["transition"])}</div>')

    return "\n".join(parts)


def render_module_structured(module_data: dict) -> str:
    """
    Render a module from structured scene data.

    module_data keys:
        title (str), faction (str), tier (str), cr (int|str),
        party_level (int|str), runtime (str), players (str),
        hook (str)            — read-aloud hook text shown before scene 1,
        hook_note (str)       — GM-only context behind the hook,
        scenes (list[dict])   — each scene dict, see _render_scene(),
        rewards (str)         — reward summary,
        dc_table (list[list]) — optional [["Scene","Check","DC","Success","Failure"],...]

    Returns a full standalone HTML string.
    """
    title      = module_data.get("title", "Untitled Module")
    faction    = module_data.get("faction", "")
    tier       = module_data.get("tier", "Standard")
    cr         = module_data.get("cr", "?")
    plevel     = module_data.get("party_level", "?")
    runtime    = module_data.get("runtime", "2-3 hours")
    players    = module_data.get("players", "4-6")
    scenes     = module_data.get("scenes", [])

    # Cover
    fc   = _faction_color(faction)
    cover = (
        f'<div class="cover" style="--faction:{fc}">'
        f'<div class="faction-label">{_esc(faction.upper())}</div>'
        f'<div class="ornament">✦ ✦ ✦</div>'
        f'<h1>{_esc(title)}</h1>'
        f'<div class="subtitle">D&amp;D 5e 2024 · One-Shot Module</div>'
        f'<div class="meta-block">'
        f'Tier: {_esc(tier.upper())} &nbsp;|&nbsp; CR {_esc(str(cr))} &nbsp;|&nbsp; '
        f'Party Level {_esc(str(plevel))} &nbsp;|&nbsp; {_esc(players)} Players'
        f'<br>Runtime: {_esc(runtime)} &nbsp;|&nbsp; {len(scenes)} Areas'
        f'</div>'
        f'</div>'
    )

    body_parts = ['<div class="page-body">']

    # Hook
    if module_data.get("hook"):
        body_parts.append(
            '<h2 style="margin-top:32px">Hook</h2>'
            '<div class="read-aloud">'
            '<span class="ra-label">📖 Read to Players Before Play Begins</span>'
            f'<em>{_esc(module_data["hook"])}</em>'
            '</div>'
        )
    if module_data.get("hook_note"):
        note_html = "<br>".join(_md(ln) for ln in module_data["hook_note"].splitlines() if ln.strip())
        body_parts.append(
            '<div class="gm-note">'
            '<span class="gm-label">📝 GM Context</span>'
            f'{note_html}'
            '</div>'
        )

    # Scene count callout
    beat_labels = {1: "Hook/Approach", 2: "Investigation", 3: "Complication",
                   4: "Climax", 5: "Resolution", 6: "Epilogue", 7: "Aftermath"}
    toc_rows = "".join(
        f'<tr><td style="font-weight:bold">{s.get("num","")}</td>'
        f'<td>{_esc(s.get("name","").title())}</td>'
        f'<td style="color:#666;font-style:italic">{_esc(s.get("beat_label", beat_labels.get(int(s.get("num",0)), "")))}</td></tr>'
        for s in scenes
    )
    body_parts.append(
        '<table style="margin-top:28px">'
        '<tr><th>#</th><th>Area</th><th>Beat</th></tr>'
        f'{toc_rows}</table>'
    )

    # Scenes
    body_parts.append('<h2 style="margin-top:48px">Areas</h2>')
    for scene in scenes:
        body_parts.append(_render_scene(scene))
        body_parts.append('<hr>')

    # Rewards
    if module_data.get("rewards"):
        body_parts.append('<h2>Rewards</h2>')
        for line in module_data["rewards"].splitlines():
            if line.strip():
                body_parts.append(f'<p style="font-family:Arial,sans-serif;font-size:15px">{_md(line)}</p>')

    # DC reference table
    if module_data.get("dc_table"):
        body_parts.append('<h2>Quick DC Reference</h2>')
        tbl_rows = []
        for ri, row in enumerate(module_data["dc_table"]):
            tag = "th" if ri == 0 else "td"
            tbl_rows.append(
                "<tr>" + "".join(f"<{tag}>{_esc(str(c))}</{tag}>" for c in row) + "</tr>"
            )
        body_parts.append("<table>" + "".join(tbl_rows) + "</table>")

    body_parts.append('</div>')

    content = cover + "\n".join(body_parts)
    return _page(f"Module — {title}", content, faction)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render_chapter(
    chapter_num: int,
    chapter_title: str,
    novel_title: str,
    body_md: str,
    faction: str = "",
) -> str:
    """Render a novel chapter as a full HTML page."""
    header = (
        f'<div class="chapter-header">'
        f'<div class="ch-label">Chapter {chapter_num} · {novel_title}</div>'
        f'<h2>{_html.escape(chapter_title)}</h2>'
        f'</div>'
    )
    content = header + _parse_blocks(body_md)
    return _page(f"Ch {chapter_num}: {chapter_title} — {novel_title}", content, faction)


def render_component(
    component_label: str,
    novel_title: str,
    body_md: str,
    faction: str = "",
) -> str:
    """Render a box-set component (DM Guide, Module, etc.) as HTML."""
    header = (
        f'<div class="chapter-header">'
        f'<div class="ch-label">{_html.escape(novel_title)}</div>'
        f'<h2>{_html.escape(component_label)}</h2>'
        f'</div>'
    )
    content = header + _parse_blocks(body_md)
    return _page(f"{component_label} — {novel_title}", content, faction)


def render_maps_page(
    novel_title: str,
    faction: str,
    image_paths: list,          # list of Path objects relative to module dir
    manifest_json: str = "",
) -> str:
    """
    Render maps.html directly from PNG paths, bypassing the markdown parser.
    Images are expected to live in a 'maps/' subdirectory relative to the page.
    """
    header = (
        f'<div class="chapter-header">'
        f'<div class="ch-label">{_html.escape(novel_title)}</div>'
        f'<h2>Maps</h2>'
        f'</div>'
    )

    if image_paths:
        figures_parts = []
        for p in image_paths:
            if p.stem.endswith("_pretty"):
                continue
            pretty = p.with_name(f"{p.stem}_pretty{p.suffix}")
            nice = p.with_name(f"{p.stem}_nice{p.suffix}")
            preview = pretty if pretty.exists() else nice
            caption = _html.escape(p.stem.replace("_", " "))
            pretty_html = (
                f'<img src="maps/{_html.escape(preview.name)}" alt="{caption} pretty" '
                f'style="max-width:100%;border-radius:8px;border:1px solid rgba(0,0,0,.15);box-shadow:0 2px 12px rgba(0,0,0,.12);">'
                if preview.exists() else
                '<div style="min-height:180px;display:flex;align-items:center;justify-content:center;'
                'border:1px dashed rgba(0,0,0,.22);border-radius:8px;color:#777;font-style:italic;">'
                'Pretty preview not generated yet</div>'
            )
            figures_parts.append(
                f'<figure style="margin:0 0 2.5rem;">'
                f'<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px;align-items:start;">'
                f'<div><div style="font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:#777;margin-bottom:6px;">VTT Tactical</div>'
                f'<img src="maps/{_html.escape(p.name)}" alt="{caption} tactical" '
                f'style="max-width:100%;border-radius:8px;border:1px solid rgba(0,0,0,.15);box-shadow:0 2px 12px rgba(0,0,0,.12);"></div>'
                f'<div><div style="font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:#777;margin-bottom:6px;">Pretty Preview</div>'
                f'{pretty_html}</div>'
                f'</div>'
                f'<figcaption style="font-size:12px;color:#888;margin-top:8px;font-family:serif;font-style:italic;">{caption}</figcaption>'
                f'</figure>'
            )
        figures = "\n".join(figures_parts)
        body_html = (
            f'<h3 style="border-bottom:1px solid rgba(0,0,0,.15);padding-bottom:.4rem;margin-bottom:1.5rem;">Battle Maps</h3>'
            f'<div style="display:flex;flex-direction:column;gap:0;">{figures}</div>'
        )
    else:
        body_html = (
            f'<p style="color:#888;font-style:italic;">No maps generated for this mission.</p>'
            + (f'<pre style="font-size:11px;color:#666;white-space:pre-wrap;">{_html.escape(manifest_json)}</pre>' if manifest_json else "")
        )

    content = header + f'<div class="chapter-body">{body_html}</div>'
    return _page(f"Maps — {novel_title}", content, faction)


def render_index(
    novel_title: str,
    faction: str,
    tier: str,
    cr,
    player_name: str,
    chapters: list[dict],
    components: list[tuple[str, str]],  # [(label, filename), ...]
    chart_pack: str | None,
    map_count: int,
) -> str:
    """Render the index page with links to all components."""
    meta = (
        f"<strong>Faction:</strong> {_html.escape(faction)} &nbsp;|&nbsp; "
        f"<strong>Tier:</strong> {_html.escape(tier.upper())} &nbsp;|&nbsp; "
        f"<strong>CR:</strong> {cr} &nbsp;|&nbsp; "
        f"<strong>Claimed by:</strong> {_html.escape(player_name or 'Open')}"
    )

    # Chapter table
    ch_rows = "".join(
        f"<tr><td>{c['num']}</td><td>"
        f"<a href='chapter_{c['num']:02d}.html'>{_html.escape(c['title'])}</a>"
        f"</td><td>{c['word_count']:,}</td></tr>"
        for c in chapters
    )
    total_words = sum(c["word_count"] for c in chapters)
    novel_section = (
        f"<h2>Novel — {total_words:,} words</h2>"
        f"<table><tr><th>#</th><th>Chapter</th><th>Words</th></tr>{ch_rows}</table>"
    )

    # Box set cards
    cards = ""
    labels = {
        "dm_guide":      ("DM Guide",       "The real situation, NPC secrets, session pacing."),
        "module":        ("Module",          "Scene-by-scene play guide with decision trees."),
        "players_guide": ("Players Guide",   "Setting lore, faction primer, surface story."),
        "maps":          ("Maps",            f"{map_count} battle maps generated."),
        "chart_pack":    ("Chart Pack",      "Stat blocks, rumors, loot, encounter tables."),
        "session":       ("▶ Run Session",   "Tablet runner — scenes, initiative, HP, debrief form."),
    }
    for slug, fname in components:
        lbl, desc = labels.get(slug, (slug.replace("_", " ").title(), ""))
        cards += (
            f'<div class="index-card">'
            f'<h3><a href="{_html.escape(fname)}">{lbl}</a></h3>'
            f'<p>{desc}</p>'
            f'</div>'
        )
    if chart_pack:
        lbl, desc = labels["chart_pack"]
        cards += (
            f'<div class="index-card">'
            f'<h3><a href="{_html.escape(chart_pack)}">{lbl}</a></h3>'
            f'<p>{desc}</p>'
            f'</div>'
        )

    # Big session runner CTA if session.html was generated
    session_cta = ""
    has_session = any(slug == "session" for slug, _ in components)
    if has_session:
        session_cta = (
            '<div style="margin:20px 0 28px;text-align:center;">'
            '<a href="session.html" style="display:inline-block;padding:16px 40px;'
            'background:#c85320;color:white;font-size:18px;font-weight:bold;'
            'border-radius:10px;text-decoration:none;letter-spacing:.04em;'
            'box-shadow:0 4px 12px rgba(200,83,32,.4);">'
            '▶ Run This Session</a>'
            '<div style="font-size:12px;color:#888;margin-top:8px;">'
            'Scene tracker · Initiative · HP · Debrief</div>'
            '</div>'
        )

    content = (
        f'<div class="chapter-header">'
        f'<div class="ch-label">Tower of Last Chance — Mission Module</div>'
        f'<h2>{_html.escape(novel_title)}</h2>'
        f'</div>'
        f'<p style="margin-bottom:16px">{meta}</p>'
        + session_cta +
        f'<h2>Box Set Components</h2>'
        f'<div class="index-grid">{cards}</div>'
        + novel_section
    )

    return _page(f"{novel_title} — Index", content, faction)
