"""
backfill_npc_outcomes.py

Fetches all messages from the mission results Discord channel, matches them to
completed NPC missions that have no outcome record, and inserts mission_outcomes rows.

Each outcome is generated by the LLM using:
  - The Discord completion/failure notice text
  - The NPC party's profile (visual, skills, history) from party_profiles table
  - The mission body and metadata

Usage:
    python scripts/backfill_npc_outcomes.py [--dry-run]

Personal missions (personal_for IS NOT NULL) are excluded.
"""

import sys, os, json, re, time, argparse
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

# Force UTF-8 output on Windows so emojis in LLM responses don't crash prints
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

from dotenv import load_dotenv
load_dotenv()

import requests
from datetime import datetime
from src.db_api import raw_query, raw_execute

RESULTS_CHANNEL_ID = "1484145986811990086"
DISCORD_TOKEN      = os.getenv("DISCORD_BOT_TOKEN", "")
HEADERS            = {"Authorization": f"Bot {DISCORD_TOKEN}"}

OLLAMA_URL   = "http://localhost:11434/api/chat"
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "gemma3:12b")

# ---------------------------------------------------------------------------
# Discord fetch
# ---------------------------------------------------------------------------

def fetch_all_messages(channel_id: str, max_pages: int = 80) -> list[dict]:
    messages = []
    before   = None
    url      = f"https://discord.com/api/v10/channels/{channel_id}/messages"

    for page in range(max_pages):
        params = {"limit": 100}
        if before:
            params["before"] = before

        resp = requests.get(url, headers=HEADERS, params=params)
        if resp.status_code == 429:
            retry = float(resp.json().get("retry_after", 2))
            print(f"  rate-limited — sleeping {retry:.1f}s")
            time.sleep(retry + 0.5)
            resp = requests.get(url, headers=HEADERS, params=params)

        if resp.status_code != 200:
            print(f"  Discord API error {resp.status_code}: {resp.text[:200]}")
            break

        batch = resp.json()
        if not batch:
            break

        messages.extend(batch)
        before = batch[-1]["id"]
        print(f"  page {page+1}: +{len(batch)} messages (total {len(messages)})")
        time.sleep(0.35)

    return messages


# ---------------------------------------------------------------------------
# Message matching
# ---------------------------------------------------------------------------

def _norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", s.lower())


def _msg_text(msg: dict) -> str:
    parts = [msg.get("content", "")]
    for emb in msg.get("embeds", []):
        parts.append(emb.get("title", ""))
        parts.append(emb.get("description", ""))
        for f in emb.get("fields", []):
            parts.append(f"{f.get('name','')} {f.get('value','')}")
    return "\n".join(p for p in parts if p)


def find_messages_for_mission(title: str, all_messages: list[dict]) -> list[dict]:
    """Return (message_dict, text) pairs whose text contains the mission title."""
    norm_title = _norm(title)
    if len(norm_title) < 6:
        return []

    hits = []
    for msg in all_messages:
        text = _msg_text(msg)
        if norm_title in _norm(text):
            hits.append({"msg": msg, "text": text})

    return hits[:6]


# ---------------------------------------------------------------------------
# Party profile lookup
# ---------------------------------------------------------------------------

def get_party_profile_blurb(party_name: str) -> str:
    """Return a compact description of the party for use in LLM prompts."""
    try:
        rows = raw_query(
            "SELECT profile_json, members_json FROM party_profiles WHERE party_name = %s LIMIT 1",
            (party_name,),
        ) or []
        if not rows:
            return ""
        row = rows[0]

        pj = row.get("profile_json") or {}
        if isinstance(pj, str):
            pj = json.loads(pj)

        mj = row.get("members_json") or []
        if isinstance(mj, str):
            mj = json.loads(mj)

        lines = []
        if pj.get("visual"):
            lines.append(f"Appearance: {pj['visual'][:200]}")
        if pj.get("specialties") or pj.get("skills"):
            lines.append(f"Skills: {pj.get('specialties') or pj.get('skills','')[:200]}")
        if pj.get("tier"):
            lines.append(f"Rank: {pj['tier']}")

        # Member list if available
        if isinstance(mj, list) and mj:
            member_names = []
            for m in mj[:6]:
                if isinstance(m, dict):
                    nm = m.get("name") or m.get("char_name") or ""
                    role = m.get("role") or m.get("class") or ""
                    if nm:
                        member_names.append(f"{nm} ({role})" if role else nm)
                elif isinstance(m, str):
                    member_names.append(m)
            if member_names:
                lines.append(f"Members: {', '.join(member_names)}")

        # Recent history (last 3 entries)
        history = pj.get("history") or []
        if history:
            lines.append("Recent history: " + " | ".join(str(h) for h in history[-3:]))

        return "\n".join(lines)
    except Exception as e:
        return ""


# ---------------------------------------------------------------------------
# LLM extraction
# ---------------------------------------------------------------------------

def _llm(prompt: str, max_tokens: int = 400) -> str:
    try:
        resp = requests.post(
            OLLAMA_URL,
            json={
                "model": OLLAMA_MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "options": {"num_predict": max_tokens, "temperature": 0.25},
                "stream": False,
            },
            timeout=180,
        )
        if resp.status_code == 200:
            return resp.json().get("message", {}).get("content", "").strip()
    except Exception as e:
        print(f"    LLM error: {e}")
    return ""


def extract_outcome(mission_row: dict, party_blurb: str, discord_hits: list[dict]) -> dict:
    title       = mission_row.get("title", "?")
    faction     = mission_row.get("faction", "")
    tier        = mission_row.get("tier", "standard")
    claim_party = mission_row.get("claim_party") or "Unknown Party"
    result      = "completed" if mission_row.get("status") == "completed" else "failed"
    mission_body = (mission_row.get("body") or "")[:300]

    # Combine Discord texts (prefer earlier messages for the claim notice, later for completion)
    combined_discord = "\n---\n".join(h["text"] for h in discord_hits[:4])

    party_section = f"\nPARTY PROFILE — {claim_party}:\n{party_blurb}" if party_blurb else ""

    prompt = f"""You are extracting structured mission outcome data for a fantasy city campaign world record.

MISSION: {title}
FACTION: {faction}
TIER: {tier}
COMPLETED BY: {claim_party}
RESULT: {result}
MISSION BRIEF: {mission_body}
{party_section}

DISCORD MESSAGES ABOUT THIS MISSION:
{combined_discord[:2000]}

Using the party's known capabilities and the Discord message content, write a realistic outcome record.
Output ONLY this JSON (no markdown fences, no explanation):
{{
  "notable_moments": "2-4 sentences describing what actually happened. Use the Discord notice as the base. Reference the party's specific capabilities or style where it fits naturally.",
  "key_decisions":    "Any notable choices made during the mission, or empty string if unknown",
  "location_changes": "Any locations damaged, destroyed, or significantly altered, or empty string",
  "loose_threads":    "Any unresolved elements, escaped enemies, or complicating factors, or empty string"
}}

Rules:
- notable_moments MUST NOT be empty — synthesize from Discord text + party profile
- Do NOT invent named NPCs killed (leave npcs_killed blank — that field is handled separately)
- Keep it grounded in the Undercity setting (sealed dome city, adventurers as economic class)
- If the mission failed, the party retreated — they survived"""

    raw = _llm(prompt, max_tokens=350)

    try:
        raw_clean = re.sub(r"```[a-z]*\n?", "", raw).strip()
        # Extract JSON if wrapped in prose
        json_match = re.search(r"\{[\s\S]*\}", raw_clean)
        if json_match:
            data = json.loads(json_match.group(0))
            return {
                "notable_moments":  str(data.get("notable_moments", "") or ""),
                "key_decisions":    str(data.get("key_decisions",    "") or ""),
                "location_changes": str(data.get("location_changes", "") or ""),
                "loose_threads":    str(data.get("loose_threads",    "") or ""),
            }
    except Exception:
        pass

    # Fallback: use raw Discord text
    return {
        "notable_moments":  discord_hits[0]["text"][:400] if discord_hits else "",
        "key_decisions":    "",
        "location_changes": "",
        "loose_threads":    "",
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    print("=== NPC Mission Outcome Backfill ===\n")

    print(f"Fetching Discord channel {RESULTS_CHANNEL_ID}...")
    all_messages = fetch_all_messages(RESULTS_CHANNEL_ID)
    print(f"Total messages: {len(all_messages)}\n")

    if not all_messages:
        print("ERROR: No messages fetched — check DISCORD_BOT_TOKEN")
        return

    # Get all NPC missions without outcomes (exclude personal missions)
    rows = raw_query("""
        SELECT m.id, m.title, m.faction, m.tier, m.status, m.posted_at,
               JSON_UNQUOTE(JSON_EXTRACT(m.mission_json, '$.claim_party'))      AS claim_party,
               JSON_UNQUOTE(JSON_EXTRACT(m.mission_json, '$.opposing_faction')) AS opposing_faction,
               JSON_UNQUOTE(JSON_EXTRACT(m.mission_json, '$.body'))             AS body
        FROM missions m
        LEFT JOIN mission_outcomes o ON o.mission_title = m.title
        WHERE m.status IN ('completed', 'failed')
          AND JSON_EXTRACT(m.mission_json, '$.personal_for') IS NULL
          AND o.id IS NULL
        ORDER BY m.id DESC
    """) or []

    print(f"NPC missions to backfill: {len(rows)}\n")

    inserted = skipped = 0

    for row in rows:
        title       = row.get("title", "Unknown")
        faction     = row.get("faction", "")
        tier        = row.get("tier", "standard")
        status      = row.get("status", "completed")
        claim_party = row.get("claim_party") or "Unknown Party"
        opposing    = row.get("opposing_faction") or ""
        result      = "completed" if status == "completed" else "failed"

        print(f"[{row['id']}] {title[:55]}")
        print(f"       party={claim_party} | result={result}")

        # Find Discord messages
        hits = find_messages_for_mission(title, all_messages)
        print(f"       discord_hits={len(hits)}")

        if not hits:
            print(f"       -> SKIP: no Discord messages found\n")
            skipped += 1
            continue

        # Get party profile
        party_blurb = get_party_profile_blurb(claim_party)

        # Completed_at: use the Discord message timestamp if available
        try:
            ts = hits[0]["msg"].get("timestamp", "")
            completed_at = datetime.fromisoformat(ts.replace("Z", "+00:00")).strftime("%Y-%m-%d")
        except Exception:
            try:
                completed_at = datetime.fromisoformat(row.get("posted_at", "")).strftime("%Y-%m-%d")
            except Exception:
                completed_at = datetime.now().strftime("%Y-%m-%d")

        # Extract outcome via LLM
        print(f"       -> calling LLM...")
        fields = extract_outcome(row, party_blurb, hits)

        if not fields["notable_moments"]:
            print(f"       -> SKIP: LLM returned empty notable_moments\n")
            skipped += 1
            continue

        print(f"       notable_moments: {fields['notable_moments'][:90]}...")

        if not args.dry_run:
            try:
                raw_execute(
                    """INSERT INTO mission_outcomes
                       (mission_title, faction, opposing_faction, tier, completed_by,
                        completed_at, result, npcs_killed, key_decisions, location_changes,
                        loose_threads, notable_moments, consequences_json)
                       VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",
                    (title, faction, opposing, tier, claim_party, completed_at,
                     result, "",
                     fields["key_decisions"], fields["location_changes"],
                     fields["loose_threads"], fields["notable_moments"],
                     "[]")
                )
                print(f"       -> INSERTED\n")
                inserted += 1
            except Exception as e:
                print(f"       -> DB ERROR: {e}\n")
                skipped += 1
        else:
            print(f"       -> DRY RUN (would insert)\n")
            inserted += 1

        time.sleep(0.15)

    print(f"\n=== Done ===")
    print(f"Inserted: {inserted} | Skipped: {skipped}")
    if args.dry_run:
        print("(dry run — nothing written)")


if __name__ == "__main__":
    main()
