"""
import_npcs_to_ddb.py — Batch-import all 199 campaign NPCs to DDB homebrew.

Reads from scripts/npc_ddb_staging.json (generated by npc_ddb_builder.py).
Uploads portraits where available. Adds movement speeds.
Logs results to logs/npc_ddb_import.log.

Run from project root:
    python scripts/import_npcs_to_ddb.py

Resumes cleanly: skips NPCs already imported (checks log for names).
"""
from __future__ import annotations

import argparse, asyncio, base64, io, json, os, re, sys
from datetime import datetime
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from dotenv import load_dotenv; load_dotenv(ROOT / ".env")

import httpx
from PIL import Image

from src.ddb_homebrew import SESSION, FORM_URL, _CR_OPTIONS, _TYPE_OPTIONS, _SIZE_OPTIONS
from src.log import logger
from scripts.fix_ebp_types_and_art import A1111_URL, _NEG, generate_art

LOG_FILE     = ROOT / "logs" / "npc_ddb_import.log"
STAGING_FILE = ROOT / "scripts" / "npc_ddb_staging.json"
ART_DIR      = ROOT / "campaign_docs" / "npc_appearances" / "npc_portraits_ddb"
ART_DIR.mkdir(parents=True, exist_ok=True)
BASE_URL     = "https://www.dndbeyond.com"

log_lines: list[str] = []

def log(msg: str):
    ts   = datetime.now().strftime("%H:%M:%S")
    line = f"[{ts}] {msg}"
    print(line, flush=True)
    log_lines.append(line)
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(line + "\n")


def _ascii(s: str) -> str:
    return s.replace("—", "--").replace("–", "-").replace("’", "'").replace("‘", "'")

def _html(s: str) -> str:
    if not s: return ""
    return "".join(f"<p>{p.replace(chr(10), '<br>').strip()}</p>"
                   for p in s.split("\n\n") if p.strip())


async def _get_csrf(url: str) -> tuple[str, str, str, str, dict]:
    hdrs = {"Accept": "text/html,application/xhtml+xml",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124"}
    try:
        async with httpx.AsyncClient(follow_redirects=False, timeout=30) as c:
            r = await c.get(url, headers=hdrs, cookies={"CobaltSession": SESSION})
            if r.status_code != 200:
                return "", "", "", "", {}
            alb     = r.cookies.get("AWSALB", "")
            albcors = r.cookies.get("AWSALBCORS", "")
            html    = r.text

        def _hid(field):
            m = re.search(r'name="' + re.escape(field) + r'"[^>]*value="([^"]*?)"', html)
            if not m:
                m = re.search(r'value="([^"]*?)"[^>]*name="' + re.escape(field) + r'"', html)
            return m.group(1) if m else ""

        obf: dict = {}
        for m in re.finditer(r"<input[^>]+>", html, re.IGNORECASE):
            inp = m.group()
            nm  = re.search(r'name="(f[a-f0-9]{30,})"', inp)
            idm = re.search(r'id="([^"]+)"', inp)
            if nm and idm:
                obf[idm.group(1)] = nm.group(1)
        for fid in ("field-avatar", "field-large-avatar"):
            m = re.search(r'id="' + re.escape(fid) + r'"[^>]*name="([^"]+)"', html, re.IGNORECASE)
            if not m:
                m = re.search(r'name="([^"]+)"[^>]*id="' + re.escape(fid) + r'"', html, re.IGNORECASE)
            if m:
                obf[fid] = m.group(1)
        return _hid("security-token"), _hid("authenticity-token"), alb, albcors, obf
    except Exception as exc:
        logger.warning("[NPC_DDB] GET error: %s", exc)
        return "", "", "", "", {}


async def add_speed(monster_id: str, movement_type: int, speed_ft: int) -> bool:
    if speed_ft == 0:
        return True
    url = f"{BASE_URL}/monster/movement/create/{monster_id}"
    sec, auth, alb, albcors, _ = await _get_csrf(url)
    if not sec:
        return False
    data    = {"security-token": sec, "authenticity-token": auth,
               "movement-type": str(movement_type), "speed": str(speed_ft)}
    cookies = {"CobaltSession": SESSION}
    if alb:
        cookies["AWSALB"] = alb; cookies["AWSALBCORS"] = albcors
    hdrs = {"Accept": "text/html,application/xhtml+xml",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124",
            "Origin": BASE_URL, "Referer": url}
    async with httpx.AsyncClient(follow_redirects=False, timeout=20) as c:
        r = await c.post(url, data=data, headers=hdrs, cookies=cookies)
    return r.status_code in (200, 301, 302, 303, 307, 308)


async def create_npc(npc: dict, image_bytes: Optional[bytes]) -> Optional[str]:
    """Create a DDB homebrew monster for an NPC. Returns edit URL or None."""
    hdrs = {"Accept": "text/html,application/xhtml+xml",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124",
            "Origin": BASE_URL, "Referer": FORM_URL}
    sec, auth, alb, albcors, obf = await _get_csrf(FORM_URL)
    if not sec:
        return None

    name    = _ascii(npc["name"])
    cr      = str(npc["cr"])
    ctype   = npc.get("creature_type", "humanoid")
    size    = npc.get("size", "M")
    ac      = npc.get("ac", 12)
    hp      = npc.get("hp", 15)
    hp_die  = str(npc.get("hp_die", "8"))
    hp_dc   = npc.get("hp_die_count", 1)
    con     = npc.get("con", 10)
    str_    = npc.get("str_", 10)
    dex     = npc.get("dex", 10)
    int_    = npc.get("int_", 10)
    wis     = npc.get("wis", 10)
    cha     = npc.get("cha", 10)
    pp      = npc.get("passive_perc", 10)
    lang    = npc.get("languages", "Common")
    saves   = npc.get("saves", {})

    actions  = _ascii(npc.get("actions", ""))
    traits   = _ascii(npc.get("traits", ""))
    reactions= _ascii(npc.get("reactions", ""))
    bonus    = _ascii(npc.get("bonus_actions", ""))
    legendary= _ascii(npc.get("legendary_actions", ""))
    mythic   = _ascii(npc.get("mythic_actions", ""))
    lair     = _ascii(npc.get("lair_actions", ""))
    notes    = _ascii(npc.get("notes", ""))

    hp_mod = ((con - 10) // 2) * hp_dc

    type_id = _TYPE_OPTIONS.get(ctype.lower(), "11")
    size_id = _SIZE_OPTIONS.get(size, "4")
    cr_id   = _CR_OPTIONS.get(cr, "5")
    die_val = hp_die if hp_die in ("4","6","8","10","12","20") else "8"

    text_data: dict = {
        "security-token":     sec,
        "authenticity-token": auth,
        "Name":               name,
        "stat-block-type":    "1",
        "monster-type":       type_id,
        "size":               size_id,
        "challenge-rating":   cr_id,
        "armor-class":        str(ac),
        "passive-perception": str(pp),
        "average-hit-points": str(hp),
        "hit-points-die-count": str(hp_dc),
        "hit-points-die-value": die_val,
        "hit-points-modifier": str(hp_mod),
        "languages-note":     lang,
        "special-traits-description-type":          "1",
        "special-traits-description-wysiwyg":       _html(traits),
        "special-traits-description":               traits,
        "actions-description-type":                 "1",
        "actions-description-wysiwyg":              _html(actions),
        "actions-description":                      actions,
        "bonus-actions-description-type":           "1",
        "bonus-actions-description-wysiwyg":        _html(bonus),
        "bonus-actions-description":                bonus,
        "reactions-description-type":               "1",
        "reactions-description-wysiwyg":            _html(reactions),
        "reactions-description":                    reactions,
        "monster-characteristics-description-type": "1",
        "monster-characteristics-description-wysiwyg": _html(notes),
        "monster-characteristics-description":      notes,
        "legendary-actions-description-type":       "1",
        "mythic-actions-description-type":          "1",
        "lair-description-type":                    "1",
    }
    if legendary:
        text_data["is-legendary"] = "y"
        text_data["legendary-actions-description-wysiwyg"] = _html(legendary)
        text_data["legendary-actions-description"]          = legendary
    if mythic:
        text_data["is-mythic"] = "y"
        text_data["mythic-actions-description-wysiwyg"] = _html(mythic)
        text_data["mythic-actions-description"]          = mythic
    if lair:
        text_data["has-lair"] = "y"
        text_data["lair-description-wysiwyg"] = _html(lair)
        text_data["lair-description"]          = lair
        text_data["lair-challenge-rating"]     = cr_id

    # Ability scores
    score_map = {
        "field-strength": str(str_), "field-dexterity": str(dex),
        "field-constitution": str(con), "field-intelligence": str(int_),
        "field-wisdom": str(wis), "field-charisma": str(cha),
        "field-initiative-bonus": str(dex - 10),
    }
    for fid, val in score_map.items():
        if fid in obf:
            text_data[obf[fid]] = val

    # Save bonuses
    save_fid = {
        "str": "field-strength-save-bonus", "dex": "field-dexterity-save-bonus",
        "con": "field-constitution-save-bonus", "int": "field-intelligence-save-bonus",
        "wis": "field-wisdom-save-bonus", "cha": "field-charisma-save-bonus",
    }
    for stat_key, fid_name in save_fid.items():
        if stat_key in saves and fid_name in obf:
            text_data[obf[fid_name]] = str(saves[stat_key])

    # Portrait
    file_data: dict = {}
    if image_bytes:
        if "field-avatar" in obf:
            file_data[obf["field-avatar"]] = ("avatar.png", image_bytes, "image/png")
        if "field-large-avatar" in obf:
            file_data[obf["field-large-avatar"]] = ("large_avatar.png", image_bytes, "image/png")

    cookies = {"CobaltSession": SESSION}
    if alb:
        cookies["AWSALB"] = alb; cookies["AWSALBCORS"] = albcors

    async with httpx.AsyncClient(follow_redirects=False, timeout=30) as c:
        resp = await c.post(
            FORM_URL, data=text_data,
            files=file_data if file_data else None,
            headers=hdrs, cookies=cookies,
        )

    if resp.status_code in (301, 302, 303, 307, 308):
        loc = resp.headers.get("location", "")
        return f"{BASE_URL}{loc}" if loc.startswith("/") else loc

    logger.warning("[NPC_DDB] POST %s for %r — no redirect", resp.status_code, name)
    return None


async def get_or_generate_portrait(npc: dict) -> Optional[bytes]:
    """Return portrait image bytes: use existing file, or generate via A1111."""
    name = npc["name"]
    safe = name.replace(" ", "_").replace("/", "_").replace("'", "").replace(",", "")

    # Cached DDB-specific portrait
    cache_path = ART_DIR / f"{safe}.png"
    if cache_path.exists():
        return cache_path.read_bytes()

    # Existing campaign portrait
    portrait_path = npc.get("portrait_path")
    if portrait_path:
        p = Path(portrait_path)
        if p.exists():
            try:
                img = Image.open(p).convert("RGBA").resize((256, 256), Image.LANCZOS)
                buf = io.BytesIO()
                img.save(buf, format="PNG")
                png = buf.getvalue()
                cache_path.write_bytes(png)
                return png
            except Exception:
                pass

    # Generate new via A1111
    sd = npc.get("sd_appearance", "")
    if not sd:
        return None
    prompt = (
        f"{sd[:300]}, "
        "D&D NPC portrait, fantasy RPG character art, "
        "dark background, detailed digital illustration, "
        "8k uhd, cinematic lighting, professional concept art"
    )
    try:
        payload = {
            "prompt":          prompt,
            "negative_prompt": _NEG,
            "width": 512, "height": 512,
            "steps": 25, "cfg_scale": 7.5,
            "sampler_name": "DPM++ 2M Karras",
            "n_iter": 1, "batch_size": 1,
        }
        async with httpx.AsyncClient(timeout=120) as client:
            r = await client.post(f"{A1111_URL}/sdapi/v1/txt2img", json=payload)
            r.raise_for_status()
            img_b64 = r.json()["images"][0]
        img = Image.open(io.BytesIO(base64.b64decode(img_b64))).convert("RGBA")
        img = img.resize((256, 256), Image.LANCZOS)
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        png = buf.getvalue()
        cache_path.write_bytes(png)
        return png
    except Exception as exc:
        logger.warning("[NPC_DDB] Art gen failed for %r: %s", name, exc)
        return None


async def main():
    staging = json.loads(STAGING_FILE.read_text(encoding="utf-8"))
    log(f"NPC DDB Import — {len(staging)} candidates")

    # Resume: load already-completed names from log
    done_names: set[str] = set()
    if LOG_FILE.exists():
        for line in LOG_FILE.read_text(encoding="utf-8").splitlines():
            if "Created:" in line or "DONE:" in line:
                # Extract name from lines like: [HH:MM:SS] DONE: Sera Voss -> https://...
                m = re.search(r"DONE: (.+?) ->", line)
                if m:
                    done_names.add(m.group(1).strip())
    if done_names:
        log(f"Resuming — {len(done_names)} already done, skipping")

    ok = 0; fail = 0; skip_art = 0

    for i, npc in enumerate(staging, 1):
        name = npc["name"]
        if name in done_names:
            continue

        status = npc.get("status", "alive")
        cr     = npc.get("cr", "1")
        level  = npc.get("level", 1)
        cls    = npc.get("cls", "?")

        log(f"[{i:03d}/{len(staging)}] {name}  CR{cr} Lv{level} {cls} [{status}]")

        # Portrait
        img = await get_or_generate_portrait(npc)
        if img:
            log(f"  Portrait OK ({len(img)//1024}KB)")
        else:
            log(f"  No portrait (importing without image)")
            skip_art += 1

        # Create DDB entry
        url = await create_npc(npc, img)
        if url:
            log(f"  DONE: {name} -> {url}")
            ok += 1
            # Add speeds
            monster_id_m = re.search(r"/monsters/(\d+)-", url)
            if monster_id_m:
                mid = monster_id_m.group(1)
                for mv_type, speed_ft in npc.get("speeds", [(1, 30)]):
                    await add_speed(mid, mv_type, speed_ft)
        else:
            log(f"  FAIL")
            fail += 1

        await asyncio.sleep(2)

    log("")
    log("=" * 60)
    log(f"Done: {ok} created, {fail} failed, {skip_art} without art")
    log(f"Log: {LOG_FILE}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--staging", default=None, help="Path to staging JSON (default: npc_ddb_staging.json)")
    ap.add_argument("--log",     default=None, help="Path to log file (default: logs/npc_ddb_import.log)")
    ap.add_argument("--art-dir", default=None, help="Portrait cache directory")
    args = ap.parse_args()
    if args.staging:
        STAGING_FILE = Path(args.staging)
    if args.log:
        LOG_FILE = Path(args.log)
    if args.art_dir:
        ART_DIR = Path(args.art_dir)
        ART_DIR.mkdir(parents=True, exist_ok=True)
    asyncio.run(main())
