"""Patch approval system for module quality learning.

Provides Discord DM interface for reviewing and approving prompt patches
generated by the self-learning quality trainer.
"""

import os
import re
import discord
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Optional

from src.log import logger

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PATCHES_FILE = PROJECT_ROOT / "skills" / "module-quality" / "PATCHES.md"


# ---------------------------------------------------------------------------
# Patch parsing
# ---------------------------------------------------------------------------

def parse_pending_patches() -> List[Dict]:
    """
    Parse PATCHES.md and return list of pending patches.
    
    Returns:
        List of dicts with: id, timestamp, mission, score, content, status_line
    """
    if not PATCHES_FILE.exists():
        return []
    
    try:
        text = PATCHES_FILE.read_text(encoding="utf-8")
    except Exception as e:
        logger.error(f"Could not read PATCHES.md: {e}")
        return []
    
    patches = []
    
    # Split by patch sessions (## Patches from ...)
    sessions = re.split(r'\n---\n\n## Patches from ', text)
    
    for i, session in enumerate(sessions[1:], start=1):  # Skip header
        # Parse session header
        lines = session.split('\n')
        if not lines:
            continue
        
        timestamp = lines[0].strip()
        mission = ""
        score = "?"
        
        # Find mission and score
        for line in lines[:10]:
            if line.startswith("**Test Mission:**"):
                mission = line.replace("**Test Mission:**", "").strip()
            elif line.startswith("**Quality Score:**"):
                score = line.replace("**Quality Score:**", "").strip()
        
        # Find individual patches (### Patch N)
        patch_sections = re.split(r'\n### Patch (\d+)\n', session)
        
        for j in range(1, len(patch_sections), 2):
            if j+1 >= len(patch_sections):
                break
                
            patch_num = patch_sections[j]
            patch_content_section = patch_sections[j+1]
            
            # Extract code block content
            code_match = re.search(r'```\n?(.*?)\n?```', patch_content_section, re.DOTALL)
            if not code_match:
                continue
            
            content = code_match.group(1).strip()
            
            # Check status
            status_match = re.search(r'\*\*Status:\*\*\s*(.*?)(?:\n|$)', patch_content_section)
            status = status_match.group(1).strip() if status_match else "PENDING"
            
            # Only include pending patches
            if "PENDING" in status or "⏳" in status:
                patch_id = f"{timestamp.replace(' ', '_').replace(':', '-')}_{patch_num}"
                patches.append({
                    "id": patch_id,
                    "num": patch_num,
                    "timestamp": timestamp,
                    "mission": mission,
                    "score": score,
                    "content": content,
                    "status": status,
                })
    
    return patches


def update_patch_status(patch_id: str, new_status: str, note: str = "") -> bool:
    """
    Update the status of a patch in PATCHES.md.
    
    Args:
        patch_id: Patch identifier (timestamp_num format)
        new_status: New status (✅ APPROVED, ❌ REJECTED, 🔄 MODIFIED)
        note: Optional note to add
    
    Returns:
        True if updated successfully
    """
    if not PATCHES_FILE.exists():
        return False
    
    try:
        text = PATCHES_FILE.read_text(encoding="utf-8")
    except Exception:
        return False
    
    # Parse patch_id to get timestamp and num
    parts = patch_id.rsplit('_', 1)
    if len(parts) != 2:
        return False
    
    timestamp_part = parts[0].replace('_', ' ').replace('-', ':')
    patch_num = parts[1]
    
    # Find and replace the status line
    # Look for pattern: ### Patch {num} ... **Status:** ⏳ PENDING
    pattern = rf'(### Patch {patch_num}\n.*?```\n.*?\n```\n\n\*\*Status:\*\*)\s*[^\n]*'
    
    timestamp_str = note if note else datetime.now().strftime("%Y-%m-%d %H:%M")
    replacement = rf'\1 {new_status} ({timestamp_str})'
    
    new_text, count = re.subn(pattern, replacement, text, flags=re.DOTALL)
    
    if count == 0:
        # Try simpler pattern
        simple_pattern = r'(\*\*Status:\*\*)\s*⏳\s*PENDING'
        # Only replace first match for this patch
        new_text = text
        found = False
        
        # Find the patch section
        session_match = re.search(rf'## Patches from {re.escape(timestamp_part)}.*?(?=\n---\n|$)', text, re.DOTALL)
        if session_match:
            session = session_match.group(0)
            patch_match = re.search(rf'### Patch {patch_num}\n.*?\*\*Status:\*\*\s*[^\n]*', session, re.DOTALL)
            if patch_match:
                old_section = patch_match.group(0)
                new_section = re.sub(r'\*\*Status:\*\*\s*⏳\s*PENDING', f'**Status:** {new_status} ({timestamp_str})', old_section)
                new_text = text.replace(old_section, new_section)
                found = True
        
        if not found:
            return False
    
    try:
        PATCHES_FILE.write_text(new_text, encoding="utf-8")
        logger.info(f"Updated patch {patch_id} to {new_status}")
        return True
    except Exception as e:
        logger.error(f"Failed to write patches file: {e}")
        return False


# ---------------------------------------------------------------------------
# Discord Views
# ---------------------------------------------------------------------------

class PatchApprovalView(discord.ui.View):
    """View with approval buttons for a single patch."""
    
    def __init__(self, patch: Dict):
        super().__init__(timeout=600)  # 10 minute timeout
        self.patch = patch
    
    @discord.ui.button(label="Approve", style=discord.ButtonStyle.green, emoji="✅")
    async def approve(self, interaction: discord.Interaction, button: discord.ui.Button):
        success = update_patch_status(self.patch["id"], "✅ APPROVED")
        if success:
            await interaction.response.edit_message(
                content=f"✅ **Patch {self.patch['num']} APPROVED**\n\n"
                        f"The patch has been marked as approved. Apply it to:\n"
                        f"• `src/agents/learning_agents.py` (ProAuthorAgent)\n"
                        f"• `src/mission_compiler.py` (section prompts)\n"
                        f"• `skills/module-quality/SKILL.md` (pattern library)",
                view=None,
            )
        else:
            await interaction.response.send_message(
                "❌ Failed to update patch status.", ephemeral=True
            )
    
    @discord.ui.button(label="Reject", style=discord.ButtonStyle.red, emoji="❌")
    async def reject(self, interaction: discord.Interaction, button: discord.ui.Button):
        success = update_patch_status(self.patch["id"], "❌ REJECTED")
        if success:
            await interaction.response.edit_message(
                content=f"❌ **Patch {self.patch['num']} REJECTED**\n\nThis patch will not be applied.",
                view=None,
            )
        else:
            await interaction.response.send_message(
                "❌ Failed to update patch status.", ephemeral=True
            )
    
    @discord.ui.button(label="Skip (Review Later)", style=discord.ButtonStyle.grey, emoji="⏭️")
    async def skip(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.edit_message(
            content=f"⏭️ **Patch {self.patch['num']} skipped** — still pending for later review.",
            view=None,
        )


class PatchListView(discord.ui.View):
    """View showing patch list with navigation."""
    
    def __init__(self, patches: List[Dict], current_index: int = 0):
        super().__init__(timeout=600)
        self.patches = patches
        self.current_index = current_index
        self._update_buttons()
    
    def _update_buttons(self):
        # Update button states based on position
        for item in self.children:
            if isinstance(item, discord.ui.Button):
                if item.custom_id == "prev":
                    item.disabled = self.current_index <= 0
                elif item.custom_id == "next":
                    item.disabled = self.current_index >= len(self.patches) - 1
    
    def _get_current_embed(self) -> discord.Embed:
        if not self.patches:
            return discord.Embed(
                title="📝 No Pending Patches",
                description="No patches are waiting for review.",
                color=discord.Color.green(),
            )
        
        patch = self.patches[self.current_index]
        
        embed = discord.Embed(
            title=f"📝 Patch {patch['num']} of {len(self.patches)}",
            color=discord.Color.blue(),
        )
        embed.add_field(
            name="📅 Generated",
            value=patch["timestamp"],
            inline=True,
        )
        embed.add_field(
            name="📊 Quality Score",
            value=patch["score"],
            inline=True,
        )
        embed.add_field(
            name="🎯 Test Mission",
            value=patch["mission"] or "Unknown",
            inline=False,
        )
        
        # Truncate content if too long
        content = patch["content"]
        if len(content) > 900:
            content = content[:900] + "\n... (truncated)"
        
        embed.add_field(
            name="💡 Proposed Prompt Addition",
            value=f"```\n{content}\n```",
            inline=False,
        )
        embed.set_footer(text=f"Patch ID: {patch['id']}")
        
        return embed
    
    @discord.ui.button(label="◀ Prev", style=discord.ButtonStyle.secondary, custom_id="prev")
    async def prev_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        self.current_index = max(0, self.current_index - 1)
        self._update_buttons()
        await interaction.response.edit_message(embed=self._get_current_embed(), view=self)
    
    @discord.ui.button(label="Approve ✅", style=discord.ButtonStyle.green, custom_id="approve")
    async def approve_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        if not self.patches:
            return
        
        patch = self.patches[self.current_index]
        success = update_patch_status(patch["id"], "✅ APPROVED")
        
        if success:
            # Remove from list and show next
            self.patches.pop(self.current_index)
            if self.current_index >= len(self.patches):
                self.current_index = max(0, len(self.patches) - 1)
            self._update_buttons()
            
            if self.patches:
                await interaction.response.edit_message(
                    content=f"✅ Patch approved! ({len(self.patches)} remaining)",
                    embed=self._get_current_embed(),
                    view=self,
                )
            else:
                await interaction.response.edit_message(
                    content="✅ All patches reviewed!",
                    embed=None,
                    view=None,
                )
        else:
            await interaction.response.send_message("❌ Failed to update.", ephemeral=True)
    
    @discord.ui.button(label="Reject ❌", style=discord.ButtonStyle.red, custom_id="reject")
    async def reject_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        if not self.patches:
            return
        
        patch = self.patches[self.current_index]
        success = update_patch_status(patch["id"], "❌ REJECTED")
        
        if success:
            self.patches.pop(self.current_index)
            if self.current_index >= len(self.patches):
                self.current_index = max(0, len(self.patches) - 1)
            self._update_buttons()
            
            if self.patches:
                await interaction.response.edit_message(
                    content=f"❌ Patch rejected. ({len(self.patches)} remaining)",
                    embed=self._get_current_embed(),
                    view=self,
                )
            else:
                await interaction.response.edit_message(
                    content="✅ All patches reviewed!",
                    embed=None,
                    view=None,
                )
        else:
            await interaction.response.send_message("❌ Failed to update.", ephemeral=True)
    
    @discord.ui.button(label="Next ▶", style=discord.ButtonStyle.secondary, custom_id="next")
    async def next_button(self, interaction: discord.Interaction, button: discord.ui.Button):
        self.current_index = min(len(self.patches) - 1, self.current_index + 1)
        self._update_buttons()
        await interaction.response.edit_message(embed=self._get_current_embed(), view=self)


# ---------------------------------------------------------------------------
# Setup function for cog registration
# ---------------------------------------------------------------------------

def setup(client):
    """Register patch approval commands."""
    
    @client.tree.command(
        name="patches",
        description="[DM only] Review pending module quality prompt patches.",
    )
    async def patches_command(interaction: discord.Interaction):
        """DM-only command to review pending patches via DM."""
        dm_user_id = int(os.getenv("DM_USER_ID", 0))
        if interaction.user.id != dm_user_id:
            await interaction.response.send_message(
                "❌ This command is restricted to the DM.", ephemeral=True
            )
            return
        
        await interaction.response.defer(ephemeral=True)
        
        # Parse pending patches
        patches = parse_pending_patches()
        
        if not patches:
            await interaction.followup.send(
                "📭 **No pending patches!**\n\n"
                "All patches have been reviewed, or no patches have been generated yet.\n"
                "Run the self-learning cycle or `python scripts/test_module_quality_training.py` to generate patches.",
                ephemeral=True,
            )
            return
        
        # Send summary
        await interaction.followup.send(
            f"📬 **{len(patches)} pending patch(es) found.**\n"
            f"Sending to your DMs for review...",
            ephemeral=True,
        )
        
        # DM the user with the patch review interface
        try:
            dm_channel = await interaction.user.create_dm()
            
            view = PatchListView(patches)
            embed = view._get_current_embed()
            
            await dm_channel.send(
                content="**🔧 Module Quality Patch Review**\n"
                        "Use the buttons to approve or reject each patch.\n"
                        "Approved patches should be manually added to the prompt files.",
                embed=embed,
                view=view,
            )
            
        except discord.Forbidden:
            await interaction.followup.send(
                "❌ Could not send DM. Please enable DMs from server members.",
                ephemeral=True,
            )
        except Exception as e:
            logger.error(f"Failed to send patch review DM: {e}")
            await interaction.followup.send(
                f"❌ Failed to send DM: {e}",
                ephemeral=True,
            )
